sudo: required
language: java
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  directories:
  - $HOME/.gradle
  - $HOME/.yarn-cache
install: "./gradlew -i -s assemble"
script:
    - "./gradlew -i -s check -DjunitVersion=4.9"
    - "./gradlew -i -s check -DjunitVersion=4.10"
    - "./gradlew -i -s check -DjunitVersion=4.11"
    - "./gradlew -i -s check -DjunitVersion=4.12"
jdk:
    - oraclejdk8
    - oraclejdk7
after_success:
    - test "$TRAVIS_JDK_VERSION" == "oraclejdk7" && test "$TRAVIS_BRANCH" == "master" && test "$TRAVIS_PULL_REQUEST" == "false" && ./gradlew overallJacocoReport coveralls uploadArchives
env:
  global:
  - secure: G7EOz25xYyIzvQwF0eKEgr+0I2S9ZO2xN6BorELeuAVDowYa2B3hJjk4zIRkc1YGWx1CTYvtOEMVVTp9nL93cn18rTNulDMPl5vvBw6t4Ag1BTovUmN2a2y7N1f4N+stmEKHmH2kUZqYSif5vYbK/2044tDtO8nfQ9/va3HxaKs=
  - secure: gAYQw79fJk+zdr8M4F5ZBWKnyA9eXfUbJQ92ucHw8OETNvawE5tqJflMkt2aCy3hTHDQmzMdI6xIGCEk6XUqe9Rydk9gESpUbErHio9FzTwlx5SQJEISOMLEb2ULe2wKn08ZfZkRITY32RUlo/vNIYDuN8xYMHN3vd1z8j97FvE=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a19193581127239cac04
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


